### ISSUE TITLE
Received an unexpected EOF or 0 bytes from the transport stream

### ISSUE THREAD

**Issue by jocull** [f0xy/forecast.io-csharp#23]
We've got a long running process that pulls lots of weather data (could be upwards of 500,000 requests). The library is stable as far as I can tell (debugging locally), but we started recording errors like this in our test environment.

My guess is there's an issue server side, like a 403 or 500 error, but it's not captured here, nor is any exception text. Is there anything we can do to start figuring out the real issue? Wasn't sure if you had ever seen this error before and might know the cause or causes.

Thanks!

```
System.Net.WebException: An exception occurred during a WebClient request. ---> System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.GZipWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.WebClient.DownloadBitsState.SetResponse(WebResponse response)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream, CompletionDelegate completionDelegate, AsyncOperation asyncOp)
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at ForecastIO.ForecastIORequest.Get()
```

**Comment by f0xy** [comment]
@jocull Any more repro steps or info from further debugging?

**Comment by jocull** [comment]
It's been too long since I worked on this for me to remember unfortunately. I think that it had something to with lots of concurrency, so maybe trying doing a batch of operations across many threads at once?
